SMODS.ConsumableType {
  key = "opusm_Reagent",
  primary_colour = HEX("867051"),
  secondary_colour = HEX("867051"),
  collection_rows = { 7, 7, 7 },
  shop_rate = 0,
  default = "c_opusm_fire",
  can_stack = true,
  can_divide = true
}

SMODS.UndiscoveredSprite {
  key = "opusm_Reagent",
  atlas = "Cards",
  path = "OpusMagnumCards.png",
  pos = { x = 4, y = 2 },
  px = 71,
  py = 95,
  no_overlay = true
}

local all_reagents = {
  { key = "fire",                  pos = { x = 5, y = 0 },   rate = 1, cost = 3 },
  { key = "water",                 pos = { x = 6, y = 0 },   rate = 1, cost = 3 },
  { key = "air",                   pos = { x = 7, y = 0 },   rate = 1, cost = 3 },
  { key = "earth",                 pos = { x = 8, y = 0 },   rate = 1, cost = 3 },
  { key = "salt",                  pos = { x = 9, y = 0 },   rate = 1, cost = 3 },
  { key = "quicksilver",           pos = { x = 10, y = 0 },  rate = 1, cost = 3 },
  { key = "lead",                  pos = { x = 11, y = 0 },  rate = 1, cost = 3 },
  { key = "tin",                   pos = { x = 5, y = 1 },   rate = 1, cost = 3 },
  { key = "iron",                  pos = { x = 6, y = 1 },   rate = 1, cost = 3 },
  { key = "copper",                pos = { x = 7, y = 1 },   rate = 1, cost = 3 },
  { key = "silver",                pos = { x = 8, y = 1 },   rate = 1, cost = 3 },
  { key = "gold",                  pos = { x = 9, y = 1 },   rate = 1, cost = 3 },
  { key = "vitae",                 pos = { x = 10, y = 1 },  rate = 1, cost = 3 },
  { key = "mors",                  pos = { x = 11, y = 1 },  rate = 1, cost = 3 },
  { key = "quintessence",          pos = { x = 5, y = 2 },   rate = 1, cost = 3 },
  { key = "stablizedfire",         pos = { x = 6, y = 2 },   rate = 1, cost = 3 },
  { key = "stablizedwater",        pos = { x = 7, y = 2 },   rate = 1, cost = 3 },
  { key = "stablizedair",          pos = { x = 8, y = 2 },   rate = 1, cost = 3 },
  { key = "stablizedearth",        pos = { x = 9, y = 2 },   rate = 1, cost = 3 },
  { key = "unstablepowder",        pos = { x = 10, y = 2 },  rate = 1, cost = 3 },
  { key = "ice",                   pos = { x = 11, y = 2 },  rate = 1, cost = 3 },
  { key = "helium",                pos = { x = 5, y = 3 },   rate = 1, cost = 3 },
  { key = "fertilizer",            pos = { x = 6, y = 3 },   rate = 1, cost = 3 },
  { key = "finesand",              pos = { x = 7, y = 3 },   rate = 1, cost = 3 },
  { key = "charcoal",              pos = { x = 8, y = 3 },   rate = 1, cost = 3 },
  { key = "bubblemix",             pos = { x = 9, y = 3 },   rate = 1, cost = 3 },
  { key = "reactivefire",          pos = { x = 10, y = 3 },  rate = 1, cost = 3 },
  { key = "reactivewater",         pos = { x = 11, y = 3 },  rate = 1, cost = 3 },
  { key = "reactiveair",           pos = { x = 5, y = 4 },   rate = 1, cost = 3 },
  { key = "reactiveearth",         pos = { x = 6, y = 4 },   rate = 1, cost = 3 },
  { key = "reactivesalt",          pos = { x = 7, y = 4 },   rate = 1, cost = 3 },
  { key = "airshipfuel",           pos = { x = 8, y = 4 },   rate = 1, cost = 3 },
  { key = "distilledwater",        pos = { x = 9, y = 4 },   rate = 1, cost = 3 },
  { key = "oxygen",                pos = { x = 10, y = 4 },  rate = 1, cost = 3 },
  { key = "slakedlime",            pos = { x = 11, y = 4 },  rate = 1, cost = 3 },
  { key = "distilledalcohol",      pos = { x = 5, y = 5 },   rate = 1, cost = 3 },
  { key = "dust",                  pos = { x = 6, y = 5 },   rate = 1, cost = 3 },
  { key = "refinedhematite",       pos = { x = 7, y = 5 },   rate = 1, cost = 3 },
  { key = "refinedmalachite",      pos = { x = 8, y = 5 },   rate = 1, cost = 3 },
  { key = "refinedcuprite",        pos = { x = 9, y = 5 },   rate = 1, cost = 3 },
  { key = "refinedmagnetite",      pos = { x = 10, y = 5 },  rate = 1, cost = 3 },
  { key = "refinedargentite",      pos = { x = 11, y = 5 },  rate = 1, cost = 3 },
  { key = "darklacquer",           pos = { x = 5, y = 6 },   rate = 1, cost = 3 },
  { key = "precisionmachineoil",   pos = { x = 6, y = 6 },   rate = 1, cost = 3 },
  { key = "poisongas",             pos = { x = 7, y = 6 },   rate = 1, cost = 3 },
  { key = "moldingsand",           pos = { x = 8, y = 6 },   rate = 1, cost = 3 },
  { key = "solder",                pos = { x = 9, y = 6 },   rate = 1, cost = 3 },
  { key = "stickyloam",            pos = { x = 10, y = 6 },  rate = 1, cost = 3 },
  { key = "capsaicin",             pos = { x = 11, y = 6 },  rate = 1, cost = 3 },
  { key = "stomachmedicine",       pos = { x = 5, y = 7 },   rate = 1, cost = 3 },
  { key = "laughinggas",           pos = { x = 6, y = 7 },   rate = 1, cost = 3 },
  { key = "wrinklecream",          pos = { x = 7, y = 7 },   rate = 1, cost = 3 },
  { key = "quenchingpowder",       pos = { x = 8, y = 7 },   rate = 1, cost = 3 },
  { key = "potash",                pos = { x = 9, y = 7 },   rate = 1, cost = 3 },
  { key = "pumice",                pos = { x = 10, y = 7 },  rate = 1, cost = 3 },
  { key = "bleach",                pos = { x = 11, y = 7 },  rate = 1, cost = 3 },
  { key = "vaporoflunacy",         pos = { x = 5, y = 8 },   rate = 1, cost = 3 },
  { key = "nitshampoo",            pos = { x = 6, y = 8 },   rate = 1, cost = 3 },
  { key = "asbestos",              pos = { x = 7, y = 8 },   rate = 1, cost = 3 },
  { key = "phlogiston",            pos = { x = 8, y = 8 },   rate = 1, cost = 3 },
  { key = "stainlesssteel",        pos = { x = 9, y = 8 },   rate = 1, cost = 3 },
  { key = "stablizedquintessence", pos = { x = 10, y = 8 },  rate = 1, cost = 3 },
  { key = "goldamalgam",           pos = { x = 11, y = 8 },  rate = 1, cost = 3 },
  { key = "silverpaint",           pos = { x = 5, y = 9 },   rate = 1, cost = 3 },
  { key = "metalliccinnabar",      pos = { x = 6, y = 9 },   rate = 1, cost = 3 },
  { key = "abrasiveparticles",     pos = { x = 7, y = 9 },   rate = 1, cost = 3 },
  { key = "vaporoflevity",         pos = { x = 8, y = 9 },   rate = 1, cost = 3 },
  { key = "ratpoison",             pos = { x = 9, y = 9 },   rate = 1, cost = 3 },
  { key = "aetherdetector",        pos = { x = 10, y = 9 },  rate = 1, cost = 3 },
  { key = "reactivecinnabar",      pos = { x = 11, y = 9 },  rate = 1, cost = 3 },
  { key = "preservativesalt",      pos = { x = 5, y = 10 },  rate = 1, cost = 3 },
  { key = "tristablizedsalt",      pos = { x = 6, y = 10 },  rate = 1, cost = 3 },
  { key = "hexastablizedsalt",     pos = { x = 7, y = 10 },  rate = 1, cost = 3 },
  { key = "lustre",                pos = { x = 8, y = 10 },  rate = 1, cost = 3 },
  { key = "tinstone",              pos = { x = 9, y = 10 },  rate = 1, cost = 3 },
  { key = "lamplightgas",          pos = { x = 10, y = 10 }, rate = 1, cost = 3 },
  { key = "conductiveenamel",      pos = { x = 11, y = 10 }, rate = 1, cost = 3 },
  { key = "weldingthermite",       pos = { x = 5, y = 11 },  rate = 1, cost = 3 },
  { key = "orangeflaresalt",       pos = { x = 6, y = 11 },  rate = 1, cost = 3 },
  { key = "greenflaresalt",        pos = { x = 7, y = 11 },  rate = 1, cost = 3 },
  { key = "hairproduct",           pos = { x = 8, y = 11 },  rate = 1, cost = 3 },
  { key = "explosivecompound",     pos = { x = 9, y = 11 },  rate = 1, cost = 3 },
  { key = "waterproofsealant",     pos = { x = 10, y = 11 }, rate = 1, cost = 3 },
  { key = "ectoplasm",             pos = { x = 11, y = 11 }, rate = 1, cost = 3 }
}

for _, v in ipairs(all_reagents) do
  SMODS.Consumable {
    set = "opusm_Reagent",
    key = v.key,
    pos = v.pos,
    cost = v.cost,
    atlas = "Cards",
    loc_vars = function(self, info_queue, card)

    end,
    can_use = function(self, card)
      return false
    end,
    use = function(self, card, area, copier)

    end
  }
end
